export const initialState = {
	session: "",
	admissionDate: "",
	admissionNo: "",
	rollNo: "",
	firstName: "",
	lastName: "",
	classId: "",
	sectionId: "",
	fatherName: "",
	contactNo: "",

	//
	gender: "",
	DOB: "",
	bloodGroup: "",
	height: "",
	weight: "",
	aadharNo: "",
	transport: "",
	religion: "",
	student: "",
	caste: "",
	nationality: "",
	registrationNo: "",
	crnNo: "",
	rte: "",
	rteApplicationNo: "",
	udiseNo: "",
	studentPhoto: "",
	casteCertificate: "",
	aadharCard: "",
	birthCertificate: "",
	transferCertificate: "",
	previousClass: "",
	passYear: "",
	obtMarks: "",
	age: "",
	schoolName: "",
	studentId: "",
	familyId: "",
	bankName: "",
	bankBranch: "",
	IFSCCode: "",
	accountNo: "",
	panNo: "",

	//
	fatherQualification: "",
	fatherOccupation: "",
	fatherIncome: "",
	fatherAadharCard: "",
	fatherPhoto: "",
	Address: "",
	fatherMobileNo: "",
	fatherEmail: "",
	motherName: "",
	motherQualification: "",
	motherOccupation: "",
	motherIncome: "",
	MotherAadharCard: "",
	motherPhoto: "",
	motherMobileNo: "",
	motherEmail: "",

	//
};
