export const initialState = {
	// ADMISSION DETAILS
	session: "",
	admissionDate: "",
	// admissionNo: "",
	firstName: "",
	lastName: "",
	contactNo: "",
	fatherName: "",
	classId: "",
	sectionId: "",
	studentType: "",
	staffNo: "",
	rte: "",
	rteApplicationNo: "",
	availingTransport: "",
	transportId: "",

	// STUDENT DETAILS

	gender: "",
	DOB: "",
	age: "",
	height: "",
	weight: "",
	bloodGroup: "",
	caste: "",
	religion: "",
	nationality: "Indian",
	aadharNo: "",
	registrationNo: "",
	udiseNo: "",
	familyId: "",
	schoolName: "",
	previousClass: "",
	passYear: "",
	obtMarks: "",
	percentage: "",

	// FAMILY DETAILS

	fatherQualification: "",
	fatherOccupation: "",
	fatherMobileNo: "",
	fatherEmail: "",
	fatherIncome: "",
	fatherAadharNo: "",
	Address: "",
	motherName: "",
	motherQualification: "",
	motherOccupation: "",
	motherIncome: "",
	motherAadharNo: "",
	motherMobileNo: "",
	motherEmail: "",
	studentId: "",
	bankName: "",
	bankBranch: "",
	IFSCCode: "",
	accountNo: "",
	panNo: "",
	uploadPanCard: "",

	// UPLOAD DOCUMENTS

	studentPhoto: "",
	aadharCard: "",
	casteCertificate: "",
	birthCertificate: "",
	transferCertificate: "",
	characterCertificate: "",
	fatherPhoto: "",
	fatherAadharCard: "",
	motherPhoto: "",
	motherAadharCard: "",
};
